<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NLPULTP7204778" failures="4" tests="9" name="PetTest" time="24.103" errors="0" timestamp="2025-06-14T16:04:57 IST">
  <testcase classname="api.tests.DDTests" name="testPostuser" time="6.481"/>
  <testcase classname="api.tests.DDTests" name="testPostuser" time="1.548"/>
  <testcase classname="api.tests.DDTests" name="testPostuser" time="1.715"/>
  <testcase classname="api.tests.DDTests" name="testPostuser" time="1.704"/>
  <testcase classname="api.tests.DDTests" name="testGetuserbyUserName" time="1.685">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testGetuserbyUserName(DDTests.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testGetuserbyUserName -->
  <testcase classname="api.tests.DDTests" name="testGetuserbyUserName" time="1.831">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testGetuserbyUserName(DDTests.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testGetuserbyUserName -->
  <testcase classname="api.tests.DDTests" name="testGetuserbyUserName" time="1.723">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testGetuserbyUserName(DDTests.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testGetuserbyUserName -->
  <testcase classname="api.tests.DDTests" name="testGetuserbyUserName" time="1.738">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.testGetuserbyUserName(DDTests.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testGetuserbyUserName -->
  <testcase classname="api.tests.DDTests" name="testDeleteuserbyUserName" time="0.001">
    <skipped/>
  </testcase> <!-- testDeleteuserbyUserName -->
</testsuite> <!-- PetTest -->
